# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f37380ddf11039db6e579e8ce6ca6d611092d38fd4886db54f51db37ef4ae0fa70253d1a19b4393bac0075ce8ddf45cda60b090b8aaeacec1043b3d1341e0755

test:
  secret_key_base: 137edd7f5ff473fecf551c304dc741f9c2a952ba770f662665d1c4eedd957cd26b222458bf67023e33659235d2da9e6ef744fba1adeaab48b0c36122b083c044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
